name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: actions/setup-cmake@v1
        with:
          cmake-version: '3.21'

      - name: Build project
        run: |
          cmake .
          make correrTests

      - name: Execute tests
        run: ./correrTests
